### PR TITLE
Starvolt

### PR DESCRIPTION
**Pull request by jimshacklock**
Mostly just updating the gearscripts to all use the new format - also a few misc fixes/updates that were in main as well

### CODE REVIEW

**Comment by Poulern** [comment]
Theres still some stuff id like to do with the gearscript (aside from getting klimas feedback). I am not confident it doesnt have bugs, and the typeof variables either need to be scrapped or fully integrated (probably scrapped, but its a missed oppertunity imo).

**Comment by calumbrookes** [comment]
not clear about what's actually being pushed here other than the new gearscript?

**Comment by jimshacklock** [comment]
It's a few updates/fixes Khaki/Poulern made to the spawn scripts and description.ext that don't seem to have already been merged in from main, so are getting picked up as changes alongside the gearscripts going from starvolt > dev

but yes it is a bit confusing (thanks github)

if we wanna hold off on the gearscript update for now we can sack this off and I can just hold it in the starvolt branch for now as it seemed like there were some bugs around only having the nato script in the new format and not the others as well

**Comment by Poulern** [comment]
Yeah just hold off on the gearscript stuff for now. I am not going to do anything with the framework for the next while so while people can use it, I don't think it should be merged into main. If you can merge the current AAF and CSAT gearscripts into dev that'd be 👍

**Comment by Rqller** [comment]
> Theres still some stuff id like to do with the gearscript (aside from getting klimas feedback). I am not confident it doesnt have bugs, and the typeof variables either need to be scrapped or fully integrated (probably scrapped, but its a missed oppertunity imo).

Been messing with the new gearscript. And generally, I think it's much better than the old gearscript. It's quicker, more intuitive, and I like the introduction of role specific backpacks. I saw you already had a discussion about the tracer/mag ratio, I think it works fine, but I imagine this also has something to do with me not being a "professional" programmer. As such, I don't see it as "incorrect" - as the discussion seemed to point to. 

I'll need to mess around with it more, the only other thing I can suggest is role specific weapons/attachments, same as the backpacks. But I understand if that'll be too complicated.

**Comment by thepaullee** [comment]
oof this is a absolute UNIT of a PR

**Review by Poulern — APPROVED** [review]
Didn't see this commit was for the development branch, merging now

**Pull request merged**
