### PR TITLE
assignGear Officer default clothing change

### PR DESCRIPTION
**Pull request by thepaullee**
IMO we don't regularly have different looking officers enough to have the default clothes be different, I kept the clothing class but just put the defaults for all factions to the default for the faction, and can be changed easily by MM if desired

### CODE REVIEW

**Comment by Poulern** [comment]
Isn't this kind of reverse logic though? We've not used officers as a gearscript class because its a pain to define manually in the gearscript, and now you want to revert this?

**Comment by jimshacklock** [comment]
This is very useful for doing things like giving certain units a different vest with a radio etc, and I'd rather leave it assigned so that it has an obvious purpose for new users when looking at the framework. Realistically we're all experienced enough with the gearscript to understand what's what, but having a bunch of unassigned stuff is going to be confusing for new mission makers. 

It's rare anyone's using vanilla gear anyway, so these will be changed 90% of the time by the mm regardless, and it doesn't cause any issues having it actually assigned.

**Comment by Poulern** [comment]
We can always change it later, for now lets try to keep the clothes on, it easy enough to fix the officer cap anyways.

**Comment by thepaullee** [comment]
my logic was that the class is still useful but the majority of the time a MM isn't using a full different set of clothing for an officer so it'll default to the same as the rest of the faction , and then only their vest has to be edited (as opposed to all 3 items) and save you a few clicks/ forgetting the class

I'm indifferent either way, just feels like CO is going to have the same uniform and helmet 99% of the time anyway

**Pull request closed without merging**
