### PR TITLE
RIP Ending #1 & disable VCOM for spawned patrols

### PR DESCRIPTION
**Pull request by thepaullee**
Replace the generic Ending #'s with actual useful ending names

### CODE REVIEW

**Comment by thepaullee** [comment]
added a commit that disables backup responding/ calling for spawned patrols and fortify units called using ca_fnc_spawnx, as in most cases this would likely mess up the mission makers intentions 

Changing to safe so AI walks during patrols instead of running

**Comment by thepaullee** [comment]
Unless I missed something with setting up LAMBS, they were spawning default settings and running as Aware

**Comment by jimshacklock** [comment]
Hmm could be the FSM doing something I guess - in game at least units with it were deffo patrolling at a walk

**Comment by calumbrookes** [comment]
"...probably not a problem to have it set on the spawned group" - can we test this and then merge?

**Comment by jimshacklock** [comment]
It occurs to me, if we're about to drop VCOM (at least temporarily), we may start hitting errors with missing functions from this as well. The Safe behaviour's fine, but lets see if we decide to retain VCOM or not after next weekend.

@thepaullee could you shelve the vcom changes and resubmit w/o them for now and I'll get this merged in

**Comment by thepaullee** [comment]
@jimshacklock boom check it out homie

**Comment by jimshacklock** [comment]
noice

**Pull request merged**
