### PR TITLE
Identity updating for assignGear factions

### PR DESCRIPTION
**Pull request by thepaullee**
Updating the "race" or nationalities of factions within assignGear

Never tried using setFace or setSpeaker so would definitely appreciate a code review and MP testing on this

### CODE REVIEW

**Comment by Poulern** [comment]
I am dubious this will work in MP and with regards to JIP. [Setface is Arguments Global and Effects local](https://community.bistudio.com/wiki/setFace), so it will not work on JIP and it will not work on spawned AI.  

I'd recommend looking at https://github.com/CombinedArmsGaming/F3_CA/blob/development/f/assignGear/fn_assignInsignia.sqf

**Comment by jimshacklock** [comment]
FWIW this is also very easily set within the spawn scripts by editing the base spawned unit for each side, perhaps it would be simpler to use that system and build on it rather than having to worry too much about the gearscripts itself. This also sorts out things like the voice protocols for different languages etc, which I don't think are tied to the faces or anything intrinsically.

**Comment by thepaullee** [comment]
> FWIW this is also very easily set within the spawn scripts by editing the base spawned unit for each side, perhaps it would be simpler to use that system and build on it rather than having to worry too much about the gearscripts itself. This also sorts out things like the voice protocols for different languages etc, which I don't think are tied to the faces or anything intrinsically.

I would disagree it's _easier_ to do within the spawn scripts just because you'd have to rely on the configs available to you in the game, ie finding a classname for a unit that fits whatever nationality your units are looking for in speech and face type 

The PR does actually set voice/ language as well, with options for Chinese and French which are a little less common. The arrays are pretty easy to edit as well so you have a lot more power to create interesting faction combos (French speaking Africans, Russian speaking East-Asians, etc)

**Comment by Poulern** [comment]
I think Starvolts solution is more elegant, easier to maintain (kinda, if we ever stop using RHS then we'd have some trouble) and more JIP compatible. For example Wallace had issues making his WW2 units speak english (brits) and instead of doing setvoice and setface, he just inserted the base unit, much quicker and easier to change.

My experience with customization in the framework is that it is very rarely used.

**Comment by thepaullee** [comment]
Reverted commits and just added comments with options for units from different identities

**Comment by Poulern** [comment]
Don't see a reason why not. The AI spawning options in the framework are 4 years old coming january, so naturally things are still a bit barebones compared to a more polished setup like lambs or the zeus zen options. Idk if its worth doing much more to it atm.

**Pull request merged**
