### PR TITLE
Headless enabled and terrainloss off

### PR DESCRIPTION
**Pull request by thepaullee**
Enabled ACEX headless with loadout transfer to prevent naked mans

Forcing ACRE terrain loss off from within framework, can accidentally be overridden by server

### CODE REVIEW

**Comment by jimshacklock** [comment]
Is there a reason we're forcing Terrain Off to be Off entirely and not to be at the usual standard of 0.2 that it's been at for ages with no issues?

**Comment by thepaullee** [comment]
#76 

@Poulern i believe you and bubbus were talking about this on Sunday?

**Comment by Poulern** [comment]
According to @Bubbus it being set to 0.2 has caused the issues for ages because ACRE2 isnt able to simulate on most maps correctly. Honestly given how often the "oh 343s are broken again" message we're getting I am willing to give his tried and true means (as in he does it for every one of his missions and they dont have any radio issues from what i can tell) of fixing it a go for the not advanced mission maker.

**Comment by Bubbus** [comment]
Terrain loss can fail pretty badly on certain maps to the point where 343 comms get totally fuzzed out within 20-30m of the sender.  It's happened multiple times and it's apparently some mildly esoteric info - so not fair on a missionmaker to have their op flop because FTs keep falling apart due to an addon bug.  Turning it off is a safe default, if a map is known to be safe for terrain loss we can recommend turning it back on as it's a fairly interesting feature when it's working correctly.

**Comment by jimshacklock** [comment]
https://acre2.idi-systems.com/wiki/frameworks/radio-signal-debugging

Probably worth doing some of this on various maps to establish what does/doesn't work then.

**Comment by Poulern** [comment]
Yeah I like limited radios as its some of the most dynamic gameplay arma has to offer. But standing in a field and having your FTL get annoyed at your AR unit 50 meters away because of a bug should have priority for our new/default mission makers

**Pull request merged**
